# Generated by Django 3.0 on 2020-01-05 18:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tickets_posted', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='departure_airport',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
