# Generated by Django 3.0 on 2020-02-13 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets_posted', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='lat_arr',
            field=models.FloatField(default=0.1),
        ),
        migrations.AddField(
            model_name='ticket',
            name='lat_dep',
            field=models.FloatField(default=0.1),
        ),
        migrations.AddField(
            model_name='ticket',
            name='lng_arr',
            field=models.FloatField(default=0.1),
        ),
        migrations.AddField(
            model_name='ticket',
            name='lng_dep',
            field=models.FloatField(default=0.1),
        ),
    ]
