# Generated by Django 3.0 on 2020-01-07 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets_posted', '0002_ticket_departure_airport'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='ticket_pdf',
            field=models.FileField(default=None, upload_to='documents/%Y/%m/%d/'),
        ),
    ]
