# Generated by Django 3.0 on 2020-01-09 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets_posted', '0003_ticket_ticket_pdf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='ticket_pdf',
        ),
    ]
