# Generated by Django 3.0 on 2020-01-09 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets_posted', '0005_ticket_is_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_pdf', models.FileField(upload_to='images/')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
