# Generated by Django 3.0 on 2020-01-09 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets_posted', '0006_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='ticket_pdf',
            field=models.FileField(upload_to='documents/%Y/%m/%d/'),
        ),
    ]
