# Generated by Django 3.0 on 2020-01-11 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets_posted', '0006_upload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upload',
            name='owner',
        ),
    ]
